# Generated by Django 6.0.1 on 2026-02-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_barres",
                    models.CharField(
                        max_length=13, unique=True, verbose_name="Code-barres (EAN13)"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom de l'article"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "prix_ht",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix HT"
                    ),
                ),
                (
                    "prix_ttc",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix TTC"
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.5,
                        max_digits=5,
                        verbose_name="Taux TVA (%)",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("boulangerie", "Boulangerie"),
                            ("produits_laitiers", "Produits laitiers"),
                            ("fruits_legumes", "Fruits et légumes"),
                            ("viande", "Viande"),
                            ("epicerie", "Épicerie"),
                            ("boissons", "Boissons"),
                        ],
                        default="epicerie",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "unite_mesure",
                    models.CharField(
                        choices=[("unite", "Unité"), ("kg", "Kg"), ("litre", "Litre")],
                        default="unite",
                        max_length=10,
                        verbose_name="Unité de mesure",
                    ),
                ),
                (
                    "stock_actuel",
                    models.PositiveIntegerField(default=0, verbose_name="Stock actuel"),
                ),
                (
                    "stock_minimum",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Stock minimum"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-created_at"],
            },
        ),
    ]
