# Generated by Django 6.0.1 on 2026-02-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["code_barres"], name="articles_ar_code_ba_6a26b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["categorie"], name="articles_ar_categor_e4fcbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["actif"], name="articles_ar_actif_d09ea0_idx"),
        ),
    ]
