# Generated by Django 6.0.1 on 2026-02-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_articles_ar_code_ba_6a26b2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_code_ba_6a26b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_categor_e4fcbc_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_actif_d09ea0_idx',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
