# Generated by Django 6.0.1 on 2026-02-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_barres', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prix_HT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_TTC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuel', models.PositiveIntegerField(default=0)),
                ('stock_minimum', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.client')),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturation.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='DetailFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_ligne', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.article')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='facturation.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retournee', models.PositiveIntegerField()),
                ('raison', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.article')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(max_length=50)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.utilisateur')),
            ],
        ),
    ]
