# Generated by Django 6.0.1 on 2026-02-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tva_taux',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
