# Generated by Django 6.0.1 on 2026-02-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_article_tva_taux'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='date',
            new_name='date_facture',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tva_taux',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant',
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='taux_TVA',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Taux en décimal (ex: 0.18 pour 18%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='article',
            name='unite_mesure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('carte', 'Carte'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('ticket_resto', 'Ticket resto'), ('mixte', 'Mixte')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_HT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_TTC',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_TVA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('payee', 'Payée'), ('annulee', 'Annulée'), ('remboursee', 'Remboursée')], default='payee', max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(blank=True, choices=[('enregistre', 'Enregistré'), ('anonyme', 'Anonyme')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('Gestionnaire', 'Gestionnaire'), ('Caissier', 'Caissier'), ('Comptable', 'Comptable')], max_length=50),
        ),
    ]
