# Generated by Django 6.0.1 on 2026-02-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_rename_date_facture_date_facture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(blank=True, choices=[('boulangerie', 'Boulangerie'), ('produits_laitiers', 'Produits laitiers'), ('fruits_legumes', 'Fruits et legumes'), ('viande', 'Viande'), ('epicerie', 'Epicerie'), ('boissons', 'Boissons'), ('alimentaire', 'Alimentaire'), ('hygiene', 'Hygiene')], default='epicerie', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='unite_mesure',
            field=models.CharField(blank=True, choices=[('unite', 'Unite'), ('kg', 'Kg'), ('litre', 'Litre'), ('piece', 'Piece'), ('sachet', 'Sachet'), ('bouteille', 'Bouteille'), ('sac', 'Sac')], default='unite', max_length=50, null=True),
        ),
    ]
