# Generated by Django 6.0.1 on 2026-02-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0006_rename_actif_utilisateur_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('mixte', 'Mixte')], max_length=20, null=True),
        ),
    ]
